In [5]:
import numpy as np
np.random.seed(0)

x = np.array([[0.2, 0.8, 0.1]])
W1 = np.random.rand(3, 4)
b1 = np.random.rand(1, 4)
W2 = np.random.rand(4, 3)
b2 = np.random.rand(1, 3)

relu = lambda z: np.maximum(0, z)
sigmoid = lambda z: 1 / (1 + np.exp(-z))
softmax = lambda z: np.exp(z) / np.sum(np.exp(z), axis=1, keepdims=True)

# (a) ReLU + Linear
h_a = relu(x @ W1 + b1)
y_a = h_a @ W2 + b2

# (b) Sigmoid + Sigmoid
h_b = sigmoid(x @ W1 + b1)
y_b = sigmoid(h_b @ W2 + b2)

# (c) ReLU + Softmax
h_c = relu(x @ W1 + b1)
y_c = softmax(h_c @ W2 + b2)

print("a) ReLU + Linear:\n", y_a)
print("\nb) Sigmoid + Sigmoid:\n", y_b)
print("\nc) ReLU + Softmax:\n", y_c)
print("\nd)Weights and Biases Shapes:")
print("W1 shape (hidden layer weights):", W1.shape)
print("b1 shape (hidden layer biases):", b1.shape)
print("W2 shape (output layer weights):", W2.shape)
print("b2 shape (output layer biases):", b2.shape)




a) ReLU + Linear:
 [[2.85935637 3.55296749 3.41089964]]

b) Sigmoid + Sigmoid:
 [[0.88360196 0.92202736 0.90706492]]

c) ReLU + Softmax:
 [[0.2111104  0.42241673 0.36647287]]

d)Weights and Biases Shapes:
W1 shape (hidden layer weights): (3, 4)
b1 shape (hidden layer biases): (1, 4)
W2 shape (output layer weights): (4, 3)
b2 shape (output layer biases): (1, 3)


In [6]:
import numpy as np
from numpy.lib.stride_tricks import as_strided

I = np.array([
    [0.2245, 0.9231, 0.2745, 0.8735, 0.3594, 0.1210],
    [0.8583, 0.4256, 0.8730, 0.3591, 0.1028, 0.7632],
    [0.1583, 0.5343, 0.7689, 0.5455, 0.2781, 0.6751],
    [0.0533, 0.0031, 0.3591, 0.2743, 0.8801, 0.3210],
    [0.3704, 0.8445, 0.0441, 0.7051, 0.6223, 0.3593],
    [0.7849, 0.5585, 0.9710, 0.5018, 0.1473, 0.1282]
])

K = np.array([
    [-0.3231, 0.0112, 0.1226],
    [ 0.1828, 0.0421,-0.1513],
    [ 0.3879, 0.7982, 0.8627]
])

def conv2d(X, K, stride=1, padding=0):
    Xp = np.pad(X, ((padding, padding), (padding, padding)))
    H, W = Xp.shape
    kH, kW = K.shape
    out_h = (H - kH) // stride + 1
    out_w = (W - kW) // stride + 1
    out = np.zeros((out_h, out_w))
    for i in range(out_h):
        for j in range(out_w):
            region = Xp[i*stride:i*stride+kH, j*stride:j*stride+kW]
            out[i, j] = np.sum(region * K)
    return out

a = conv2d(I, K, stride=1, padding=0)
b = conv2d(I, K, stride=2, padding=0)
c = conv2d(I, K, stride=2, padding=1)

print("a) stride=1, no padding:\n", np.round(a,4))
print("\nb) stride=2, no padding:\n", np.round(b,4))
print("\nc) stride=2, padding=1:\n", np.round(c,4))


a) stride=1, no padding:
 [[1.1654 1.1637 1.0979 0.7071]
 [0.1025 0.4883 0.9735 1.0738]
 [0.8604 0.8481 0.8526 1.0285]
 [1.7114 1.5108 0.8428 0.4841]]

b) stride=2, no padding:
 [[1.1654 1.0979]
 [0.8604 0.8526]]

c) stride=2, padding=1:
 [[0.922  1.2199 1.0363]
 [0.0328 0.4883 1.0738]
 [0.9971 1.5108 0.4841]]


In [7]:
import numpy as np

def pool2d(X, size=3, stride=None, mode='max'):
    if stride is None:
        stride = size
    H, W = X.shape
    out_h = (H - size) // stride + 1
    out_w = (W - size) // stride + 1
    out = np.zeros((out_h, out_w))
    for i in range(out_h):
        for j in range(out_w):
            region = X[i*stride:i*stride+size, j*stride:j*stride+size]
            if mode == 'max':
                out[i, j] = np.max(region)
            elif mode == 'avg':
                out[i, j] = np.mean(region)
    return out

# (a) Max-pooling 3x3
maxpool = pool2d(I, size=3, mode='max')

# (b) Average-pooling 3x3
avgpool = pool2d(I, size=3, mode='avg')

# (c) Global max-pooling
global_max = np.max(I)

# (d) Global average-pooling
global_avg = np.mean(I)

print("a) Max-pooling 3x3:\n", np.round(maxpool,4))
print("\nb) Average-pooling 3x3:\n", np.round(avgpool,4))
print("\nc) Global max-pooling:\n", np.round(global_max,4))
print("\nd) Global average-pooling:\n", np.round(global_avg,4))


a) Max-pooling 3x3:
 [[0.9231 0.8735]
 [0.971  0.8801]]

b) Average-pooling 3x3:
 [[0.5601 0.4531]
 [0.4432 0.4377]]

c) Global max-pooling:
 0.971

d) Global average-pooling:
 0.4735
